export const value = {
  properties: [
    {
      name: "Palm Harbour",
      id: 1,
      price: 2.095,
      addr: "Delhi",
      movIn: 2,

      bed: 2,
      bath: 2,
      size: "5x7",
    },
    {
      name: "Baverly Hill",
      id: 2,
      price: 5.87,
      addr: "Delhi",
      movIn: 0,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Faulker Avenue",
      id: 3,
      price: 2.095,
      addr: "Chennai",
      movIn: 6,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Palm Hill",
      id: 4,
      price: 7,
      addr: "Kolkata",
      movIn: 12,

      bed: 2,
      bath: 2,
      size: "5x9",
    },
    {
      name: "Victor Palace",
      id: 5,
      price: 12.095,
      addr: "Delhi",
      movIn: 8,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Swiss ViewPark",
      id: 6,
      price: 3.095,
      addr: "Bangalore",
      movIn: 0,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi City View",
      id: 7,
      price: 10.095,
      addr: "Delhi",
      movIn: 1,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Victor Palm Village",
      id: 8,
      price: 3.095,
      addr: "Chennai",
      movIn: 3,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Palm HarbourII",
      id: 9,
      price: 4.095,
      addr: "Bangalore",
      movIn: 1,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Swiss ViewParkII",
      id: 6,
      price: 2.095,
      addr: "Bangalore",
      movIn: 0,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Palm HarbourIII",
      id: 9,
      price: 5.095,
      addr: "Bangalore",
      movIn: 1,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage",
      id: 2,
      price: 6.095,
      addr: "Bangalore",
      movIn: 1,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage II",
      id: 1,
      price: 7.095,
      addr: "Bangalore",
      movIn: 1,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore CityView",
      id: 1,
      price: 8.095,
      addr: "Bangalore",
      movIn: 1,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore CityView II",
      id: 3,
      price: 9.095,
      addr: "Bangalore",
      movIn: 1,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage III",
      id: 6,
      price: 9.025,
      addr: "Bangalore",
      movIn: 1,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore PlayField",
      id: 1,
      price: 11.095,
      addr: "Bangalore",
      movIn: 1,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore PlayField II",
      id: 3,
      price: 12.095,
      addr: "Bangalore",
      movIn: 1,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Bangalore",
      movIn: 1,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage",
      id: 2,
      price: 6.095,
      addr: "Bangalore",
      movIn: 3,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage II",
      id: 1,
      price: 7.095,
      addr: "Bangalore",
      movIn: 3,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore CityView",
      id: 1,
      price: 8.095,
      addr: "Bangalore",
      movIn: 3,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore CityView II",
      id: 3,
      price: 9.095,
      addr: "Bangalore",
      movIn: 3,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage III",
      id: 6,
      price: 9.025,
      addr: "Bangalore",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore PlayField",
      id: 1,
      price: 11.095,
      addr: "Bangalore",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore PlayField II",
      id: 3,
      price: 12.095,
      addr: "Bangalore",
      movIn: 3,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Bangalore",
      movIn: 4,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandi",
      id: 5,
      price: 1.095,
      addr: "Bangalore",
      movIn: 4,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandi II",
      id: 2,
      price: 2.095,
      addr: "Bangalore",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Paradise",
      id: 9,
      price: 1.095,
      addr: "Bangalore",
      movIn: 4,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandini",
      id: 1,
      price: 4.095,
      addr: "Bangalore",
      movIn: 4,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandi III",
      id: 3,
      price: 4.095,
      addr: "Bangalore",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Paradise",
      id: 4,
      price: 4.15,
      addr: "Bangalore",
      movIn: 4,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage",
      id: 2,
      price: 6.095,
      addr: "Bangalore",
      movIn: 5,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage II",
      id: 1,
      price: 7.095,
      addr: "Bangalore",
      movIn: 5,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore CityView",
      id: 1,
      price: 8.095,
      addr: "Bangalore",
      movIn: 5,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore CityView II",
      id: 3,
      price: 9.095,
      addr: "Bangalore",
      movIn: 5,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage III",
      id: 6,
      price: 9.025,
      addr: "Bangalore",
      movIn: 6,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore PlayField",
      id: 1,
      price: 11.095,
      addr: "Bangalore",
      movIn: 6,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore PlayField II",
      id: 3,
      price: 12.095,
      addr: "Bangalore",
      movIn: 5,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Bangalore",
      movIn: 6,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandi",
      id: 5,
      price: 1.095,
      addr: "Bangalore",
      movIn: 6,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandi II",
      id: 2,
      price: 2.095,
      addr: "Bangalore",
      movIn: 6,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Paradise",
      id: 9,
      price: 1.095,
      addr: "Bangalore",
      movIn: 6,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandini",
      id: 1,
      price: 4.095,
      addr: "Bangalore",
      movIn: 6,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandi III",
      id: 3,
      price: 4.095,
      addr: "Bangalore",
      movIn: 7,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Paradise",
      id: 4,
      price: 4.15,
      addr: "Bangalore",
      movIn: 7,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage",
      id: 2,
      price: 6.095,
      addr: "Bangalore",
      movIn: 8,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage II",
      id: 1,
      price: 7.095,
      addr: "Bangalore",
      movIn: 8,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore CityView",
      id: 1,
      price: 8.095,
      addr: "Bangalore",
      movIn: 8,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore CityView II",
      id: 3,
      price: 9.095,
      addr: "Bangalore",
      movIn: 8,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage III",
      id: 6,
      price: 9.025,
      addr: "Bangalore",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore PlayField",
      id: 1,
      price: 11.095,
      addr: "Bangalore",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore PlayField II",
      id: 3,
      price: 12.095,
      addr: "Bangalore",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Bangalore",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandi",
      id: 5,
      price: 1.095,
      addr: "Bangalore",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandi II",
      id: 2,
      price: 2.095,
      addr: "Bangalore",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Paradise",
      id: 9,
      price: 1.095,
      addr: "Bangalore",
      movIn: 9,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandini",
      id: 1,
      price: 4.095,
      addr: "Bangalore",
      movIn: 9,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandi III",
      id: 3,
      price: 4.095,
      addr: "Bangalore",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Paradise",
      id: 4,
      price: 4.15,
      addr: "Bangalore",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage",
      id: 2,
      price: 6.095,
      addr: "Bangalore",
      movIn: 11,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage II",
      id: 1,
      price: 7.095,
      addr: "Bangalore",
      movIn: 11,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore CityView",
      id: 1,
      price: 8.095,
      addr: "Bangalore",
      movIn: 11,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore CityView II",
      id: 3,
      price: 9.095,
      addr: "Bangalore",
      movIn: 11,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage III",
      id: 6,
      price: 9.025,
      addr: "Bangalore",
      movIn: 12,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore PlayField",
      id: 1,
      price: 11.095,
      addr: "Bangalore",
      movIn: 12,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore PlayField II",
      id: 3,
      price: 12.095,
      addr: "Bangalore",
      movIn: 13,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Bangalore",
      movIn: 14,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandi",
      id: 5,
      price: 1.095,
      addr: "Bangalore",
      movIn: 14,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandi II",
      id: 2,
      price: 2.095,
      addr: "Bangalore",
      movIn: 14,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Paradise",
      id: 9,
      price: 1.095,
      addr: "Bangalore",
      movIn: 14,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandini",
      id: 1,
      price: 4.095,
      addr: "Bangalore",
      movIn: 14,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Nandi III",
      id: 3,
      price: 4.095,
      addr: "Bangalore",
      movIn: 12,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Paradise",
      id: 4,
      price: 4.15,
      addr: "Bangalore",
      movIn: 13,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage",
      id: 2,
      price: 6.095,
      addr: "Delhi",
      movIn: 3,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage II",
      id: 1,
      price: 7.095,
      addr: "Delhi",
      movIn: 3,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi CityView",
      id: 1,
      price: 8.095,
      addr: "Delhi",
      movIn: 3,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi CityView II",
      id: 3,
      price: 9.095,
      addr: "Delhi",
      movIn: 3,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage III",
      id: 6,
      price: 9.025,
      addr: "Delhi",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi PlayField",
      id: 1,
      price: 11.095,
      addr: "Delhi",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi PlayField II",
      id: 3,
      price: 12.095,
      addr: "Delhi",
      movIn: 3,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Delhi",
      movIn: 4,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandi",
      id: 5,
      price: 1.095,
      addr: "Delhi",
      movIn: 4,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandi II",
      id: 2,
      price: 2.095,
      addr: "Delhi",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Paradise",
      id: 9,
      price: 1.095,
      addr: "Delhi",
      movIn: 4,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandini",
      id: 1,
      price: 4.095,
      addr: "Delhi",
      movIn: 4,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandi III",
      id: 3,
      price: 4.095,
      addr: "Delhi",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Paradise",
      id: 4,
      price: 4.15,
      addr: "Delhi",
      movIn: 4,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage",
      id: 2,
      price: 6.095,
      addr: "Delhi",
      movIn: 5,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage II",
      id: 1,
      price: 7.095,
      addr: "Delhi",
      movIn: 5,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi CityView",
      id: 1,
      price: 8.095,
      addr: "Delhi",
      movIn: 5,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi CityView II",
      id: 3,
      price: 9.095,
      addr: "Delhi",
      movIn: 5,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage III",
      id: 6,
      price: 9.025,
      addr: "Delhi",
      movIn: 6,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi PlayField",
      id: 1,
      price: 11.095,
      addr: "Delhi",
      movIn: 6,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi PlayField II",
      id: 3,
      price: 12.095,
      addr: "Delhi",
      movIn: 5,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Delhi",
      movIn: 6,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandi",
      id: 5,
      price: 1.095,
      addr: "Delhi",
      movIn: 6,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandi II",
      id: 2,
      price: 2.095,
      addr: "Delhi",
      movIn: 6,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Paradise",
      id: 9,
      price: 1.095,
      addr: "Delhi",
      movIn: 6,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandini",
      id: 1,
      price: 4.095,
      addr: "Delhi",
      movIn: 6,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandi III",
      id: 3,
      price: 4.095,
      addr: "Delhi",
      movIn: 7,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Paradise",
      id: 4,
      price: 4.15,
      addr: "Delhi",
      movIn: 7,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage",
      id: 2,
      price: 6.095,
      addr: "Delhi",
      movIn: 8,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage II",
      id: 1,
      price: 7.095,
      addr: "Delhi",
      movIn: 8,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi CityView",
      id: 1,
      price: 8.095,
      addr: "Delhi",
      movIn: 8,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi CityView II",
      id: 3,
      price: 9.095,
      addr: "Delhi",
      movIn: 8,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage III",
      id: 6,
      price: 9.025,
      addr: "Delhi",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi PlayField",
      id: 1,
      price: 11.095,
      addr: "Delhi",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi PlayField II",
      id: 3,
      price: 12.095,
      addr: "Delhi",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Delhi",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandi",
      id: 5,
      price: 1.095,
      addr: "Delhi",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandi II",
      id: 2,
      price: 2.095,
      addr: "Delhi",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Paradise",
      id: 9,
      price: 1.095,
      addr: "Delhi",
      movIn: 9,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandini",
      id: 1,
      price: 4.095,
      addr: "Delhi",
      movIn: 9,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandi III",
      id: 3,
      price: 4.095,
      addr: "Delhi",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Paradise",
      id: 4,
      price: 4.15,
      addr: "Delhi",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage",
      id: 2,
      price: 6.095,
      addr: "Delhi",
      movIn: 11,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage II",
      id: 1,
      price: 7.095,
      addr: "Delhi",
      movIn: 11,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi CityView",
      id: 1,
      price: 8.095,
      addr: "Delhi",
      movIn: 11,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi CityView II",
      id: 3,
      price: 9.095,
      addr: "Delhi",
      movIn: 11,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage III",
      id: 6,
      price: 9.025,
      addr: "Delhi",
      movIn: 12,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi PlayField",
      id: 1,
      price: 11.095,
      addr: "Delhi",
      movIn: 12,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi PlayField II",
      id: 3,
      price: 12.095,
      addr: "Delhi",
      movIn: 13,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Delhi",
      movIn: 14,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandi",
      id: 5,
      price: 1.095,
      addr: "Delhi",
      movIn: 14,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandi II",
      id: 2,
      price: 2.095,
      addr: "Delhi",
      movIn: 14,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Paradise",
      id: 9,
      price: 1.095,
      addr: "Delhi",
      movIn: 14,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandini",
      id: 1,
      price: 4.095,
      addr: "Delhi",
      movIn: 14,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Nandi III",
      id: 3,
      price: 4.095,
      addr: "Delhi",
      movIn: 12,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Delhi Paradise",
      id: 4,
      price: 4.15,
      addr: "Delhi",
      movIn: 13,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage",
      id: 2,
      price: 6.095,
      addr: "Chennai",
      movIn: 3,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage II",
      id: 1,
      price: 7.095,
      addr: "Chennai",
      movIn: 3,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai CityView",
      id: 1,
      price: 8.095,
      addr: "Chennai",
      movIn: 3,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai CityView II",
      id: 3,
      price: 9.095,
      addr: "Chennai",
      movIn: 3,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage III",
      id: 6,
      price: 9.025,
      addr: "Chennai",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai PlayField",
      id: 1,
      price: 11.095,
      addr: "Chennai",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai PlayField II",
      id: 3,
      price: 12.095,
      addr: "Chennai",
      movIn: 3,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Chennai",
      movIn: 4,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandi",
      id: 5,
      price: 1.095,
      addr: "Chennai",
      movIn: 4,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandi II",
      id: 2,
      price: 2.095,
      addr: "Chennai",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Paradise",
      id: 9,
      price: 1.095,
      addr: "Chennai",
      movIn: 4,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandini",
      id: 1,
      price: 4.095,
      addr: "Chennai",
      movIn: 4,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandi III",
      id: 3,
      price: 4.095,
      addr: "Chennai",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Paradise",
      id: 4,
      price: 4.15,
      addr: "Chennai",
      movIn: 4,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage",
      id: 2,
      price: 6.095,
      addr: "Chennai",
      movIn: 5,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage II",
      id: 1,
      price: 7.095,
      addr: "Chennai",
      movIn: 5,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai CityView",
      id: 1,
      price: 8.095,
      addr: "Chennai",
      movIn: 5,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai CityView II",
      id: 3,
      price: 9.095,
      addr: "Chennai",
      movIn: 5,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage III",
      id: 6,
      price: 9.025,
      addr: "Chennai",
      movIn: 6,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai PlayField",
      id: 1,
      price: 11.095,
      addr: "Chennai",
      movIn: 6,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai PlayField II",
      id: 3,
      price: 12.095,
      addr: "Chennai",
      movIn: 5,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Chennai",
      movIn: 6,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandi",
      id: 5,
      price: 1.095,
      addr: "Chennai",
      movIn: 6,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandi II",
      id: 2,
      price: 2.095,
      addr: "Chennai",
      movIn: 6,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Paradise",
      id: 9,
      price: 1.095,
      addr: "Chennai",
      movIn: 6,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandini",
      id: 1,
      price: 4.095,
      addr: "Chennai",
      movIn: 6,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandi III",
      id: 3,
      price: 4.095,
      addr: "Chennai",
      movIn: 7,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Paradise",
      id: 4,
      price: 4.15,
      addr: "Chennai",
      movIn: 7,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage",
      id: 2,
      price: 6.095,
      addr: "Chennai",
      movIn: 8,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage II",
      id: 1,
      price: 7.095,
      addr: "Chennai",
      movIn: 8,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai CityView",
      id: 1,
      price: 8.095,
      addr: "Chennai",
      movIn: 8,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai CityView II",
      id: 3,
      price: 9.095,
      addr: "Chennai",
      movIn: 8,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage III",
      id: 6,
      price: 9.025,
      addr: "Chennai",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai PlayField",
      id: 1,
      price: 11.095,
      addr: "Chennai",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai PlayField II",
      id: 3,
      price: 12.095,
      addr: "Chennai",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Chennai",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandi",
      id: 5,
      price: 1.095,
      addr: "Chennai",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandi II",
      id: 2,
      price: 2.095,
      addr: "Chennai",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Paradise",
      id: 9,
      price: 1.095,
      addr: "Chennai",
      movIn: 9,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandini",
      id: 1,
      price: 4.095,
      addr: "Chennai",
      movIn: 9,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandi III",
      id: 3,
      price: 4.095,
      addr: "Chennai",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Paradise",
      id: 4,
      price: 4.15,
      addr: "Chennai",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage",
      id: 2,
      price: 6.095,
      addr: "Chennai",
      movIn: 11,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage II",
      id: 1,
      price: 7.095,
      addr: "Chennai",
      movIn: 11,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai CityView",
      id: 1,
      price: 8.095,
      addr: "Chennai",
      movIn: 11,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai CityView II",
      id: 3,
      price: 9.095,
      addr: "Chennai",
      movIn: 11,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage III",
      id: 6,
      price: 9.025,
      addr: "Chennai",
      movIn: 12,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai PlayField",
      id: 1,
      price: 11.095,
      addr: "Chennai",
      movIn: 12,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai PlayField II",
      id: 3,
      price: 12.095,
      addr: "Chennai",
      movIn: 13,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Chennai",
      movIn: 14,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandi",
      id: 5,
      price: 1.095,
      addr: "Chennai",
      movIn: 14,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandi II",
      id: 2,
      price: 2.095,
      addr: "Chennai",
      movIn: 14,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Paradise",
      id: 9,
      price: 1.095,
      addr: "Chennai",
      movIn: 14,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandini",
      id: 1,
      price: 4.095,
      addr: "Chennai",
      movIn: 14,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Nandi III",
      id: 3,
      price: 4.095,
      addr: "Chennai",
      movIn: 12,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Chennai Paradise",
      id: 4,
      price: 4.15,
      addr: "Chennai",
      movIn: 13,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Bangalore Vintage",
      id: 2,
      price: 6.095,
      addr: "Kolkata",
      movIn: 3,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage II",
      id: 1,
      price: 7.095,
      addr: "Kolkata",
      movIn: 3,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata CityView",
      id: 1,
      price: 8.095,
      addr: "Kolkata",
      movIn: 3,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata CityView II",
      id: 3,
      price: 9.095,
      addr: "Kolkata",
      movIn: 3,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage III",
      id: 6,
      price: 9.025,
      addr: "Kolkata",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata PlayField",
      id: 1,
      price: 11.095,
      addr: "Kolkata",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata PlayField II",
      id: 3,
      price: 12.095,
      addr: "Kolkata",
      movIn: 3,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Kolkata",
      movIn: 4,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandi",
      id: 5,
      price: 1.095,
      addr: "Kolkata",
      movIn: 4,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandi II",
      id: 2,
      price: 2.095,
      addr: "Kolkata",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Paradise",
      id: 9,
      price: 1.095,
      addr: "Kolkata",
      movIn: 4,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandini",
      id: 1,
      price: 4.095,
      addr: "Kolkata",
      movIn: 4,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandi III",
      id: 3,
      price: 4.095,
      addr: "Kolkata",
      movIn: 4,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Paradise",
      id: 4,
      price: 4.15,
      addr: "Kolkata",
      movIn: 4,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage",
      id: 2,
      price: 6.095,
      addr: "Kolkata",
      movIn: 5,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage II",
      id: 1,
      price: 7.095,
      addr: "Kolkata",
      movIn: 5,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata CityView",
      id: 1,
      price: 8.095,
      addr: "Kolkata",
      movIn: 5,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata CityView II",
      id: 3,
      price: 9.095,
      addr: "Kolkata",
      movIn: 5,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage III",
      id: 6,
      price: 9.025,
      addr: "Kolkata",
      movIn: 6,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata PlayField",
      id: 1,
      price: 11.095,
      addr: "Kolkata",
      movIn: 6,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata PlayField II",
      id: 3,
      price: 12.095,
      addr: "Kolkata",
      movIn: 5,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Kolkata",
      movIn: 6,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandi",
      id: 5,
      price: 1.095,
      addr: "Kolkata",
      movIn: 6,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandi II",
      id: 2,
      price: 2.095,
      addr: "Kolkata",
      movIn: 6,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Paradise",
      id: 9,
      price: 1.095,
      addr: "Kolkata",
      movIn: 6,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandini",
      id: 1,
      price: 4.095,
      addr: "Kolkata",
      movIn: 6,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandi III",
      id: 3,
      price: 4.095,
      addr: "Kolkata",
      movIn: 7,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Paradise",
      id: 4,
      price: 4.15,
      addr: "Kolkata",
      movIn: 7,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage",
      id: 2,
      price: 6.095,
      addr: "Kolkata",
      movIn: 8,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage II",
      id: 1,
      price: 7.095,
      addr: "Kolkata",
      movIn: 8,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata CityView",
      id: 1,
      price: 8.095,
      addr: "Kolkata",
      movIn: 8,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata CityView II",
      id: 3,
      price: 9.095,
      addr: "Kolkata",
      movIn: 8,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage III",
      id: 6,
      price: 9.025,
      addr: "Kolkata",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata PlayField",
      id: 1,
      price: 11.095,
      addr: "Kolkata",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata PlayField II",
      id: 3,
      price: 12.095,
      addr: "Kolkata",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Kolkata",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandi",
      id: 5,
      price: 1.095,
      addr: "Kolkata",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandi II",
      id: 2,
      price: 2.095,
      addr: "Kolkata",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Paradise",
      id: 9,
      price: 1.095,
      addr: "Kolkata",
      movIn: 9,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandini",
      id: 1,
      price: 4.095,
      addr: "Kolkata",
      movIn: 9,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandi III",
      id: 3,
      price: 4.095,
      addr: "Kolkata",
      movIn: 9,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Paradise",
      id: 4,
      price: 4.15,
      addr: "Kolkata",
      movIn: 9,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage",
      id: 2,
      price: 6.095,
      addr: "Kolkata",
      movIn: 11,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage II",
      id: 1,
      price: 7.095,
      addr: "Kolkata",
      movIn: 11,

      bed: 4,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata CityView",
      id: 1,
      price: 8.095,
      addr: "Kolkata",
      movIn: 11,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata CityView II",
      id: 3,
      price: 9.095,
      addr: "Kolkata",
      movIn: 11,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage III",
      id: 6,
      price: 9.025,
      addr: "Kolkata",
      movIn: 12,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata PlayField",
      id: 1,
      price: 11.095,
      addr: "Kolkata",
      movIn: 12,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata PlayField II",
      id: 3,
      price: 12.095,
      addr: "Kolkata",
      movIn: 13,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Vintage IV",
      id: 8,
      price: 13.095,
      addr: "Kolkata",
      movIn: 14,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandi",
      id: 5,
      price: 1.095,
      addr: "Kolkata",
      movIn: 14,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandi II",
      id: 2,
      price: 2.095,
      addr: "Kolkata",
      movIn: 14,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Paradise",
      id: 9,
      price: 1.095,
      addr: "Kolkata",
      movIn: 14,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandini",
      id: 1,
      price: 4.095,
      addr: "Kolkata",
      movIn: 14,

      bed: 1,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Nandi III",
      id: 3,
      price: 4.095,
      addr: "Kolkata",
      movIn: 12,

      bed: 2,
      bath: 1,
      size: "5x9",
    },
    {
      name: "Kolkata Paradise",
      id: 4,
      price: 4.15,
      addr: "Kolkata",
      movIn: 13,

      bed: 3,
      bath: 1,
      size: "5x9",
    },
  ],
};
export function getName(i) {
  return value.properties[i].name;
}
export function getPrice(i) {
  return value.properties[i].price;
}
export function getAddr(i) {
  return value.properties[i].addr;
}
export function getBed(i) {
  return value.properties[i].bed;
}
export function getBath(i) {
  return value.properties[i].bath;
}
export function getSize(i) {
  return value.properties[i].size;
}
export function getmovIn(i) {
  return value.properties[i].movIn;
}
export function nameMatch(m, arr) {
  return arr.filter((e) => e.name.toLowerCase().includes(m.toLowerCase()));
}
export function locationMatch(m, arr) {
  return arr.filter((e) => e.addr === m);
}
export function priceMatch(m, n, arr) {
  return arr.filter((e) => e.price >= m && e.price < n);
}
export function BedMath(m, arr) {
  return arr.filter((e) => e.bed == m);
}
export function movmatch(m, n, arr) {
  return arr.filter((e) => e.movIn >= m && e.movIn < n);
}
